longhorn/backing-image-manager

pkg/server/backing_image.go
Signed-off-by: Shuo Wu <shuo@rancher.com>
=> Fix bug that UUID is not set

pkg/server/backing_image.go
Signed-off-by: Shuo Wu <shuo@rancher.com>
=> Set download progress to 100 for transferred images

.drone.yml
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>
=> Add drone configuration

pkg/server/server_test.go
After the backing image manager initialization, the test suite can
not modify the fields used in the manager monitor goroutines.
=> Fix the race in the unit test

package/Dockerfile
Signed-off-by: David Ko <dko@suse.com>
ref: https://github.com/longhorn/longhorn/issues/2763
=> Frequently update packages when building image

pkg/datasource/handler.go, pkg/datasource/server.go
This PR fixes the issue mentioned in https://github.com/longhorn/longhorn/issues/2404#issuecomment-897523851
=> Add 60s wait limit for backing image data source processing start

pkg/datasource/util.go
https://github.com/longhorn/longhorn/issues/3174
=> Skip writing zero byte for backing image download or upload

Dockerfile.dapper, package/Dockerfile
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>
=> update v1_20210422 base image

.drone.yml
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>
=> update drone config

pkg/client/manager_client.go
Longhorn/longhorn#3838
Signed-off-by: Derek Su <derek.su@suse.com>
=> Fix connection leak

Dockerfile.dapper, package/Dockerfile
Ref: https://github.com/longhorn/longhorn/issues/2939
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>
=> change base image to SUSE BCI

pkg/datasource/server_test.go
Longhorn/longhorn#3733
See https://github.com/longhorn/backing-image-manager/pull/49#discussion_r850466506 for details
=> datasource: Update the test file size to avoid potential alignment issue

.drone.yml, Dockerfile.dapper, pkg/server/handler.go, scripts/package
This PR adds support for building on s390x architecture.
=> Add s390x support

pkg/datasource/handler.go, pkg/server/backing_image.go
https://github.com/longhorn/longhorn/issues/2285
https://github.com/longhorn/longhorn/issues/3546
=> Implement storage-network

pkg/sync/router.go
Signed-off-by: Shuo Wu <shuo.wu@suse.com>
=> Add pprof service

pkg/sync/handler.go, pkg/sync/service.go, pkg/sync/sync_file.go, pkg/util/http_util.go
https://github.com/longhorn/longhorn/issues/4074
=> Fix the download or upload timeout not working issue

pkg/manager/service.go
Signed-off-by: Shuo Wu <shuo.wu@suse.com>
=> manager: Fix the flooded broadcasting issue

pkg/sync/service.go, pkg/sync/sync_file.go
https://github.com/longhorn/longhorn/issues/4085
=> Reuse the backing images after upgrading from v1.1.x

pkg/manager/service.go, pkg/sync/sync_file.go, pkg/util/util.go
=> Release the port correctly

pkg/server/manager.go
=> [v1.2.x]server: Check the work directory in the monitor

Dockerfile.dapper, package/Dockerfile
Dockerfile: update the path to devel tools repo
For https://github.com/longhorn/longhorn/issues/4949
Signed-off-by: Yang Chiu <yang.chiu@suse.com>
=> Dockerfile: update the path to devel tools repo

pkg/sync/sync_file.go
ref: https://github.com/longhorn/longhorn/issues/4852, https://github.com/harvester/harvester/issues/3123
**Test Step**
1. Install LH and set the `default-backing-image-manager-image` setting to this branch.
2. Create a BackingImage with a invalid checksum. We can see the `state` of the BackingImage will get into `failed`.
=> fix(sync_file): return error to handlerFailureNoLock

go.mod, go.sum, pkg/sync/service.go, pkg/types/types.go, vendor/github.com/longhorn/sparse-tools/sparse/client.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/5110
depends on https://github.com/longhorn/sparse-tools/pull/84
Signed-off-by: Derek Su [derek.su@suse.com](mailto:derek.su@suse.com)
=> Make replica's sync server HTTP client timeout configurable

go.mod, go.sum, pkg/sync/service.go, pkg/types/types.go, vendor/github.com/longhorn/sparse-tools/sparse/client.go, vendor/github.com/longhorn/sparse-tools/sparse/fiemap.go, vendor/github.com/longhorn/sparse-tools/sparse/file.go, vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go, vendor/github.com/longhorn/sparse-tools/sparse/rest/router.go, vendor/github.com/longhorn/sparse-tools/sparse/rest/server.go, vendor/github.com/longhorn/sparse-tools/sparse/sfold.go, vendor/github.com/longhorn/sparse-tools/sparse/sprune.go, vendor/github.com/longhorn/sparse-tools/types/types.go, vendor/github.com/longhorn/sparse-tools/util/file.go, vendor/github.com/longhorn/sparse-tools/util/hash.go, vendor/modules.txt
Longhorn/longhorn#5110
Signed-off-by: Derek Su <derek.su@suse.com>
=> [BACKPORT][V1.4.0] Make replica's sync server HTTP client timeout configurable

go.mod, go.sum, vendor/github.com/longhorn/sparse-tools/sparse/client.go, vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go, vendor/modules.txt
Bump github.com/longhorn/sparse-tools from v0.0.0-20230216042534-6e4173e9def4 to v0.0.0-20230327064700-b60b990a105b
=> [BACKPORT][v1.4.x] chore(deps): bump github.com/longhorn/sparse-tools

go.mod, go.sum, vendor/github.com/longhorn/sparse-tools/sparse/rest/server.go, vendor/modules.txt
Issue: [longhorn/longhorn#4305](https://github.com/longhorn/longhorn/issues/4305)
Depends on: https://github.com/longhorn/sparse-tools/pull/93
=> vendor: update sparse-tools

pkg/manager/server_test.go, pkg/sync/server_test.go, pkg/sync/service.go, pkg/util/util.go
ref: https://github.com/longhorn/longhorn/issues/7295
=> feat(download): compress backingimage when download

app/cmd/data_source.go
ref: https://github.com/longhorn/longhorn/issues/7822
url could contain "=" in query parameters
=> [MANUALLY BACKPORT v1.5.x] fix(datasource): fix url parsing

README.md
N/A
This adds information that I hope will be useful to newcomers learning how all the pieces of Longhorn interact.
=> README.md: add brief description of operation and links to docs

pkg/client/manager_client.go
=> fix(lint): replace grpc Dial with NewClient

Dockerfile.dapper, package/Dockerfile
ref: longhorn/longhorn#8721
Issue #8721
=> ci: use golang bci instead of manual download

pkg/util/util.go
=> Skip lint check for grpc.DialContext and grpc.WithBlock

.github/workflows/build.yml, scripts/package
Multiplatform build support on CI workflow.
=> fix(ci): multiplatform build

pkg/manager/service.go
Issue `None`
Cleanup import.
`None`
`None`
=> chore(import): cleanup

pkg/manager/service.go
Issue longhorn/longhorn#2259
Support for IPv6.
`None`
`None`
=> feat(ipv6): support address family
